### PR TITLE
chore: whitelist storage items that are read every block

### PR DESCRIPTION
**Pull request by gregdhill**

### CODE REVIEW

**Comment by sander2** [comment]
Is there any consequence if a whitelisted storage item is _not_ read every block?

**Comment by gregdhill** [comment]
> Is there any consequence if a whitelisted storage item is _not_ read every block?

The idea is that benchmarks which use this storage value will not consider that for the final weight since it is already read `on_initialize` they should be cached. If the item is _not_ read then the benchmark will slightly underestimate the cost.

**Comment by sander2** [comment]
If all benchmarks ignore it, wouldn't it always underestimate the real cost since it also excludes the first read inside `on_initialize`? Or is that considered to be neglectable?

**Comment by gregdhill** [comment]
I think it's negligible.

**Pull request merged**
